I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 162, in script call
    call hover1
  File "game/script.rpy", line 162, in script call
    call hover1
ScriptError: could not find label 'hover1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 162, in script call
    call hover1
  File "/Users/lily/Downloads/renpy-8.2.0-sdk/renpy/ast.py", line 1416, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 162, in script call
    call hover1
  File "/Users/lily/Downloads/renpy-8.2.0-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'hover1'.

macOS-14.4-arm64-arm-64bit arm64
Ren'Py 8.2.0.24012702
Serious Games 1.8
Wed Apr 10 23:49:37 2024
