I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Short-Scripts.rpy", line 12, in script
    $ random_scene = renpy.random.choice(scenario_numbers)
  File "game/Short-Scripts.rpy", line 12, in <module>
    $ random_scene = renpy.random.choice(scenario_numbers)
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Short-Scripts.rpy", line 12, in script
    $ random_scene = renpy.random.choice(scenario_numbers)
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/Short-Scripts.rpy", line 12, in <module>
    $ random_scene = renpy.random.choice(scenario_numbers)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/random.py", line 346, in choice
  File "D:\renpy-8.0.3-sdk\renpy\revertable.py", line 217, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
Serious Games 1.8
Mon Dec  4 17:34:06 2023
